name: desktop
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <email@example.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  encrypt: ^3.3.1
  win32: ^1.7.4
  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
